#!/usr/bin/env bash
#
#
# Robert Carson <robert.carson@gmail.com>

export ALLOW_FLIGHT=${ALLOW_FLIGHT:-false}
export ALLOW_NETHER=${ALLOW_NETHER:-true}
export DIFFICULTY=${DIFFICULTY:-3}
export ENABLE_COMMAND_BLOCK=${ENABLE_COMMAND_BLOCK:-false}
export ENABLE_QUERY=${ENABLE_QUERY:-false}
export ENABLE_RCON=${ENABLE_RCON:-false}
export FORCE_GAMEMODE=${FORCE_GAMEMODE:-false}
export GAMEMODE=${GAMEMODE:-0}
export GENERATE_STRUCTURES=${GENERATE_STRUCTURES:-true}
export GENERATOR_SETTINGS=${GENERATOR_SETTINGS:-}
export HARDCORE=${HARDCORE:-false}
export LEVEL_NAME=${LEVEL_NAME:-world}
export LEVEL_SEED=${LEVEL_SEED:-}
export LEVEL_TYPE=${LEVEL_TYPE:-DEFAULT}
export MAX_BUILD_HEIGHT=${MAX_BUILD_HEIGHT:-256}
export MAX_PLAYERS=${MAX_PLAYERS:-10}
export MAX_TICK_TIME=${MAX_TICK_TIME:-60000}
export MAX_WORLD_SIZE=${MAX_WORLD_SIZE:-29999984}
export MOTD=${MOTD:-A Minecraft Server}
export NETWORK_COMPRESSION_THRESHOLD=${NETWORK_COMPRESSION_THRESHOLD:-256}
export ONLINE_MODE=${ONLINE_MODE:-true}
export OP_PERMISSION_LEVEL=${OP_PERMISSION_LEVEL:-4}
export PLAYER_IDLE_TIMEOUT=${PLAYER_IDLE_TIMEOUT:-0}
export PREVENT_PROXY_CONNECTIONS=${PREVENT_PROXY_CONNECTIONS:-false}
export PVP=${PVP:-true}
export RCON_PASSWORD=${RCON_PASSWORD:-}
export RESOURCE_PACK=${RESOURCE_PACK:-}
export RESOURCE_PACK_SHA1=${RESOURCE_PACK_SHA1:-}
export SERVER_IP=${SERVER_IP:-}
export SERVER_PORT=${SERVER_PORT:-25565}
export SNOOPER_ENABLED=${SNOOPER_ENABLED:-false}
export SPAWN_ANIMALS=${SPAWN_ANIMALS:-true}
export SPAWN_MONSTERS=${SPAWN_MONSTERS:-true}
export SPAWN_NPCS=${SPAWN_NPCS:-true}
export USE_NATIVE_TRANSPORT=${USE_NATIVE_TRANSPORT:-true}
export VIEW_DISTANCE=${VIEW_DISTANCE:-10}
export WHITE_LIST=${WHITE_LIST:-false}

function render_template_file {
    local template="${1}"
    local file="${template%.*}"

    if [[ -e "${file}" ]]; then
        copy_reference_file "${file}"
        return $?
    fi
    
    envsubst < "${template}" > "${file}"
    copy_reference_file "${file}"
}
    
function copy_reference_file {
    local file="${1}"
    local basedir="/usr/share/minecraft/ref/"
    local target="${MINECRAFT_HOME:-/var/lib/minecraft}"
    local extension="${file##*.}"

    if [[ ${extension} == 'tmpl' ]]; then
        render_template_file "${file}"
    else
        relative_path="${file//${basedir}}"
        relative_dirs="$(dirname "${relative_path}")"

        if [[ ${relative_dirs} != '.' ]]; then
            target="${target}/${relative_dirs}"
            mkdir -p "${target}"
        fi

        if [[ -e "${target}/$(basename "${file}")" ]]; then
            echo "Target already exists."
            return 0
        fi

        echo "installing ${file} -> ${target}"
        cp "${file}" "${target}"
    fi
}
